name: Build tauri app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6

    - name: Install dependencies
      shell: bash
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev
         elif [ "$RUNNER_OS" == "Windows" ]; then
              curl -o webview2_installer.exe https://go.microsoft.com/fwlink/p/?LinkId=2124703
              ./webview2_installer.exe
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi

    - name: Yarn Install
      run: |
        yarn install

    - name: Build
      run: |
        yarn tauri build
      env:
        # Needs to be set to false otherwise build wont work currently
        CI: "false"

    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          src-tauri/target/release/bundle/deb/stracciatella-*.deb
          src-tauri/target/release/bundle/appimage/stracciatella-*.AppImage
          src-tauri/target/release/stracciatella-*.exe
