name: Build tauri app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6

    - name: Build
      run: |
        yarn install
        yarn tauri build
